config = {
    "j5":{
        "direction": -1,
        "iprobe": "in5",
        "iprobe_val": 1,
        "joint_val": 0,
        "forward": 1000000,
        "backward": -1000000,
        "vel_forward": 5,
        "vel_backward": 10,
        "halt_accel": 1,
        "trigger_count": 1,
        "stop": 50,
    },
    "j6":{
        "direction": -1,
        "iprobe": "in6",
        "iprobe_val": 1,
        "joint_val": 0,
        "forward": 1000000,
        "backward": -1000000,
        "vel_forward": 5,
        "vel_backward": 10,
        "halt_accel": 1,
        "trigger_count": 1,
        "stop": 50,
    },
    "j7":{
        "direction": -1,
        "iprobe": "in7",
        "iprobe_val": 1,
        "joint_val": 0,
        "forward": 1000000,
        "backward": -1000000,
        "vel_forward": 5,
        "vel_backward": 10,
        "halt_accel": 1,
        "trigger_count": 1,
        "stop": 50,
    },                          
}
